name: maela_antigens_env
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
# archive
  - mamba
  - libarchive
# R
  - r-base=4.2.1
  - r-rcpp>1.0
  - r-magrittr=2.0.3
  - r-tidyverse=1.3.2
  - r-ggrepel
  - r-tsne>=0.1, <0.2
  - r-ggforce
  - bioconductor-simlr>1.20, <1.26
  - r-rstatix=0.7.0
  - r-ggpubr=0.4.0
  - r-e1071
  - r-cowplot
  - r-kableextra
  - r-ggbeeswarm
  - r-corrr=0.4.4
  - r-multcomp
  - r-viridis
  - r-lme4>=1.1, <1.2
  - r-sjplot
  - r-moments
  - r-umap=0.2.10.0
  - r-rmarkdown=2.23
  - r-cli
  - r-glue
  - r-rlang=1.1.1
  - r-tibble
  - conda-forge:r-cpp11=0.4.4
  - r-archive=1.1.5
  - r-svglite=2.1.0
  - r-rjava=1.0
  - r-nnet=7.3
  - r-ggmsa
